import { ConvexReactClient } from "convex/react";

// Initialize Convex client
// The CONVEX_URL will be set via environment variable or .env file
const convexUrl = import.meta.env.VITE_CONVEX_URL;

// Only create client if URL is provided (must be absolute URL)
let convex;
if (convexUrl && convexUrl.startsWith("http")) {
  try {
    convex = new ConvexReactClient(convexUrl);
  } catch (err) {
    // Failed to create Convex client
    // Fallback to placeholder to prevent crashes
    convex = new ConvexReactClient("https://placeholder.convex.cloud");
  }
} else {
  // Create a dummy client that won't work but won't throw errors
  // This allows the app to run without Convex configured
  // Don't log warning if URL is intentionally not set (development)
  if (convexUrl !== undefined) {
    // VITE_CONVEX_URL not set or invalid
  }
  // Use a placeholder URL that won't be used
  convex = new ConvexReactClient("https://placeholder.convex.cloud");
}

export { convex };

// Import and export Convex API (generated by Convex when you run npx convex dev)
// Default API structure for when Convex isn't configured
const defaultApi = { 
  events: { 
    list: null 
  } 
};

// Try to import the generated API
// Use dynamic import that works in browser
let api: any = defaultApi;

// Load API asynchronously - this runs when module loads
import('../convex/_generated/api.js')
  .then((apiModule) => {
    if (apiModule && apiModule.api) {
      api = apiModule.api;
    }
  })
  .catch(() => {
    // File doesn't exist - use default (this is fine)
    api = defaultApi;
  });

export { api };
